import type { Metadata } from "next";
import "./globals.css";
import SideNav from "./ui/Sidenav";
import { AuthProvider } from "./providers/AuthProvider";

export const metadata: Metadata = {
  title: "MyBaseNextJs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black font-sans">
        <AuthProvider>
          <main className="flex bg-black min-h-screen">
            <SideNav />
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
