import type { Metadata } from "next";
import "./globals.css";
import SideNav from "./ui/Sidenav";

export const metadata: Metadata = {
  title: "MyBaseNextJs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black font-sans">
        <main className="flex bg-black">
          <SideNav />
          {children}
        </main>
      </body>
    </html>
  );
}
